### ISSUE TITLE
Double checking regarding error messages

### ISSUE THREAD

**Issue by computron** [hackingmaterials/jobflow#3]
I just want to double check there are clear error messages if:

- Someone tries to return a non-MSONable object in a job
- An activity is constructed with cycles in the job
- If you try to set the "output" of an Activity to a function

**Comment by utf** [comment]
> Someone tries to return a non-MSONable object in a job

```python
raise RuntimeError(
    "Job output contained an object that is not MSONable and therefore "
    "could not be serialized."
)
```

> An activity is constructed with cycles in the job

```python
raise ValueError(
    "Job connectivity contains cycles therefore job execution order "
    "cannot be determined."
)
```

> If you try to set the "output" of an Activity to a function

It is not possible to call functions on OutputReference objects, this will cause the normal python exception `AttributeError: 'OutputReference' object has no attribute 'missing_function'`.

I also added a warning if you try and set the output of Flow to a Job or another flow, instead of an OutputReference.

```python
warnings.warn(
    f"Flow '{self.name}' contains a Flow or Job as an output. "
    "Usually the Flow output should be the output of a Job or "
    "another Flow (e.g. job.output). If this message is "
    "unexpected then double check the outputs of your Flow."
)
```
